package oracle.bi.web.soap;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import sitronics.data.utils.Consts;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll?wsdl",
  targetNamespace="urn://oracle.bi.webservices/v6", name="SecurityService")
public class SecurityService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("oracle.bi.web.soap.SecurityService");
      URL baseUrl = SecurityService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SecurityService.class.getResource(Consts.BI_ANALYTICS_URL + "/analytics/saw.dll?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, Consts.BI_ANALYTICS_URL + "/analytics/saw.dll?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, Consts.BI_ANALYTICS_URL + "/analytics/saw.dll?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using " + Consts.BI_ANALYTICS_URL + "/analytics/saw.dll?wsdl",
          e);
    }
  }

  public SecurityService()
  {
    super(wsdlLocationURL,
          new QName("urn://oracle.bi.webservices/v6", "SecurityService"));
  }

  public SecurityService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SecurityServiceSoap")
  public oracle.bi.web.soap.SecurityServiceSoap getSecurityServiceSoap()
  {
    return (oracle.bi.web.soap.SecurityServiceSoap) super.getPort(new QName("urn://oracle.bi.webservices/v6",
                                                                            "SecurityServiceSoap"),
                                                                  oracle.bi.web.soap.SecurityServiceSoap.class);
  }

  @WebEndpoint(name="SecurityServiceSoap")
  public oracle.bi.web.soap.SecurityServiceSoap getSecurityServiceSoap(WebServiceFeature... features)
  {
    return (oracle.bi.web.soap.SecurityServiceSoap) super.getPort(new QName("urn://oracle.bi.webservices/v6",
                                                                            "SecurityServiceSoap"),
                                                                  oracle.bi.web.soap.SecurityServiceSoap.class,
                                                                  features);
  }
}
