package oracle.bi.web.soap;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll?wsdl",
  targetNamespace="urn://oracle.bi.webservices/v6", name="SecurityServiceSoap")
@XmlSeeAlso(
  { oracle.bi.web.soap.ObjectFactory.class })
public interface SecurityServiceSoap
{
  @WebMethod(action="#getGlobalPrivileges")
  @Action(input="#getGlobalPrivileges", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getGlobalPrivilegesResponse")
  @ResponseWrapper(localName="getGlobalPrivilegesResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetGlobalPrivilegesResult")
  @RequestWrapper(localName="getGlobalPrivileges", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetGlobalPrivileges")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="sawPrivileges")
  public List<oracle.bi.web.soap.Privilege> getGlobalPrivileges(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getGlobalPrivilegeACL")
  @Action(input="#getGlobalPrivilegeACL", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getGlobalPrivilegeACLResponse")
  @ResponseWrapper(localName="getGlobalPrivilegeACLResult",
    targetNamespace="urn://oracle.bi.webservices/v6", className="oracle.bi.web.soap.GetGlobalPrivilegeACLResult")
  @RequestWrapper(localName="getGlobalPrivilegeACL", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetGlobalPrivilegeACL")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="acl")
  public oracle.bi.web.soap.ACL getGlobalPrivilegeACL(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="privilegeName")
    String privilegeName, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#updateGlobalPrivilegeACL")
  @Action(input="#updateGlobalPrivilegeACL", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/updateGlobalPrivilegeACLResponse")
  @ResponseWrapper(localName="updateGlobalPrivilegeACLResult",
    targetNamespace="urn://oracle.bi.webservices/v6", className="oracle.bi.web.soap.UpdateGlobalPrivilegeACLResult")
  @RequestWrapper(localName="updateGlobalPrivilegeACL", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.UpdateGlobalPrivilegeACL")
  public void updateGlobalPrivilegeACL(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="privilegeName")
    String privilegeName, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="acl")
    oracle.bi.web.soap.ACL acl, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="updateACLParams")
    oracle.bi.web.soap.UpdateACLParams updateACLParams,
    @WebParam(targetNamespace="urn://oracle.bi.webservices/v6", name="sessionID")
    String sessionID);

  @WebMethod(action="#forgetAccounts")
  @Action(input="#forgetAccounts", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/forgetAccountsResponse")
  @ResponseWrapper(localName="forgetAccountsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.ForgetAccountsResult")
  @RequestWrapper(localName="forgetAccounts", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.ForgetAccounts")
  public void forgetAccounts(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="account")
    List<oracle.bi.web.soap.Account> account, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="cleanuplevel")
    int cleanuplevel, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#renameAccounts")
  @Action(input="#renameAccounts", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/renameAccountsResponse")
  @ResponseWrapper(localName="renameAccountsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.RenameAccountsResult")
  @RequestWrapper(localName="renameAccounts", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.RenameAccounts")
  public void renameAccounts(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="from")
    List<oracle.bi.web.soap.Account> from, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="to")
    List<oracle.bi.web.soap.Account> to, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#joinGroups")
  @Action(input="#joinGroups", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/joinGroupsResponse")
  @ResponseWrapper(localName="joinGroupsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.JoinGroupsResult")
  @RequestWrapper(localName="joinGroups", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.JoinGroups")
  public void joinGroups(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="group")
    List<oracle.bi.web.soap.Account> group, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="member")
    List<oracle.bi.web.soap.Account> member, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#leaveGroups")
  @Action(input="#leaveGroups", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/leaveGroupsResponse")
  @ResponseWrapper(localName="leaveGroupsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.LeaveGroupsResult")
  @RequestWrapper(localName="leaveGroups", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.LeaveGroups")
  public void leaveGroups(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="group")
    List<oracle.bi.web.soap.Account> group, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="member")
    List<oracle.bi.web.soap.Account> member, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getGroups")
  @Action(input="#getGroups", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getGroupsResponse")
  @ResponseWrapper(localName="getGroupsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetGroupsResult")
  @RequestWrapper(localName="getGroups", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetGroups")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="account")
  public List<oracle.bi.web.soap.Account> getGroups(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="member")
    List<oracle.bi.web.soap.Account> member, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="expandGroups")
    Boolean expandGroups, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getMembers")
  @Action(input="#getMembers", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getMembersResponse")
  @ResponseWrapper(localName="getMembersResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetMembersResult")
  @RequestWrapper(localName="getMembers", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetMembers")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="account")
  public List<oracle.bi.web.soap.Account> getMembers(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="group")
    List<oracle.bi.web.soap.Account> group, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="expandGroups")
    Boolean expandGroups, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#isMember")
  @Action(input="#isMember", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/isMemberResponse")
  @ResponseWrapper(localName="isMemberResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.IsMemberResult")
  @RequestWrapper(localName="isMember", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.IsMember")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="result")
  public boolean isMember(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="group")
    List<oracle.bi.web.soap.Account> group, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="member")
    List<oracle.bi.web.soap.Account> member, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="expandGroups")
    Boolean expandGroups, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getPermissions")
  @Action(input="#getPermissions", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getPermissionsResponse")
  @ResponseWrapper(localName="getPermissionsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetPermissionsResult")
  @RequestWrapper(localName="getPermissions", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetPermissions")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6")
  public List<Integer> getPermissions(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="acls")
    List<oracle.bi.web.soap.ACL> acls, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="account")
    oracle.bi.web.soap.Account account, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getPrivilegesStatus")
  @Action(input="#getPrivilegesStatus", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getPrivilegesStatusResponse")
  @ResponseWrapper(localName="getPrivilegesStatusResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetPrivilegesStatusResult")
  @RequestWrapper(localName="getPrivilegesStatus", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetPrivilegesStatus")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6")
  public List<Boolean> getPrivilegesStatus(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="privileges")
    List<String> privileges, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);

  @WebMethod(action="#getAccounts")
  @Action(input="#getAccounts", output="urn://oracle.bi.webservices/v6/SecurityServiceSoap/getAccountsResponse")
  @ResponseWrapper(localName="getAccountsResult", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetAccountsResult")
  @RequestWrapper(localName="getAccounts", targetNamespace="urn://oracle.bi.webservices/v6",
    className="oracle.bi.web.soap.GetAccounts")
  @WebResult(targetNamespace="urn://oracle.bi.webservices/v6", name="accountDetails")
  public List<oracle.bi.web.soap.Account> getAccounts(@WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="account")
    List<oracle.bi.web.soap.Account> account, @WebParam(targetNamespace="urn://oracle.bi.webservices/v6",
      name="sessionID")
    String sessionID);
}
